/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "Guardrail": {
      "id": string
      "type": "sst.sst.Linkable"
      "version": string
    }
    "ObservabilidadOtlpEndpoint": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ObservabilidadOtlpHeaders": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}

import "sst"
export {}