"""Draw the catalog Workflows as Mermaid diagrams, straight from the code.

LlamaIndex derives a Workflow's graph from the type hints of its @step methods: each step
consumes one event type and returns others. `get_workflow_representation` reads that graph,
so these diagrams cannot drift from the code. Regenerate after changing a step signature:

    uv run python scripts/draw_workflows.py          # writes docs/workflows.md
"""

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "core/src"))

from llama_index.core.agent.workflow import FunctionAgent  # noqa: E402
from workflows.representation import WorkflowStepNode, get_workflow_representation  # noqa: E402

from catalog.v1 import MappingV1  # noqa: E402
from catalog.v2 import MappingV2  # noqa: E402

OUTPUT = ROOT / "docs/workflows.md"

WORKFLOWS = [
    ("V1 · `MappingV1`", MappingV1,
     "Two steps and no tools: `prepare` builds the messages and `map` makes one structured call."),
    ("V2 · `MappingV2`", MappingV2,
     "Four steps. `check_cache` and `resolve` can end the run without the model; "
     "`run_agent` runs the FunctionAgent below."),
    ("Inside `run_agent` · LlamaIndex `FunctionAgent`", FunctionAgent,
     "The library's own loop. `submit_listing` is `return_direct`: a valid submission ends the "
     "loop in `aggregate_tool_results`; a validation error goes back to the model as a tool result."),
]


def edges(workflow) -> list[tuple[str, str]]:
    """(source, target) for every edge of the library's graph, sorted so the output is stable."""
    return sorted((e.source, e.target) for e in get_workflow_representation(workflow).edges)


def mermaid(workflow) -> str:
    graph = get_workflow_representation(workflow)
    lines = ["flowchart LR"]
    for node in sorted(graph.nodes, key=lambda n: n.id):
        # Steps are boxes, events are rounded pills.
        lines.append(f"  {node.id}[{node.id}]" if isinstance(node, WorkflowStepNode)
                     else f"  {node.id}([{node.id}])")
    lines += [f"  {source} --> {target}" for source, target in edges(workflow)]
    lines += ["  classDef step fill:#123a3a,stroke:#69e0c5,color:#fff",
              "  class " + ",".join(sorted(n.id for n in graph.nodes if isinstance(n, WorkflowStepNode))) + " step"]
    return "\n".join(lines)


def render() -> str:
    parts = ["# Catalog Workflows",
             "",
             "Generated by `scripts/draw_workflows.py` from the step signatures "
             "(`get_workflow_representation`). Boxes are steps, pills are events. Do not edit by hand.",
             ""]
    for title, workflow, note in WORKFLOWS:
        parts += [f"## {title}", "", note, "", "```mermaid", mermaid(workflow), "```", ""]
    return "\n".join(parts)


if __name__ == "__main__":
    OUTPUT.write_text(render(), encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
